<?php

namespace Tests\Unit\Http\Requests;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\ChannelRequest
 */
class ChannelRequestTest extends TestCase
{
    /** @var \App\Http\Requests\ChannelRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\ChannelRequest();
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'type' => [
                'required',
                'string',
            ],
            'description' => [
                'string',
                'nullable',
            ],
        ], $actual);
    }

    // test cases...
}
