<?php

namespace Tests\Unit\Http\Requests;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\MonitorRequest
 */
class MonitorRequestTest extends TestCase
{
    /** @var \App\Http\Requests\MonitorRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\MonitorRequest();
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'url' => [
                'required',
                'string',
                'url',
                'active_url',
            ],
            'certificate_check_enabled' => [
                'boolean',
            ],
            'look_for_string' => [
                'string',
                'nullable',
            ],
            'uptime_check_enabled' => [
                'boolean',
            ],
        ], $actual);
    }

    // test cases...
}
